{
 "title": "Crypto BIG DATA Dashboard",
 "tags": [
  "airflow",
  "crypto",
  "bigdata"
 ],
 "refresh": "1m",
 "panels": [
  {
   "title": "Market Dominance (Top 5)",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT name, market_cap_usd FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY market_cap_usd DESC LIMIT 5"
    }
   ]
  },
  {
   "title": "Top Gainers (24h)",
   "type": "bargauge",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT name, change_percent_24h FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY change_percent_24h DESC LIMIT 5"
    }
   ]
  },
  {
   "title": "Top Losers (24h)",
   "type": "bargauge",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT name, change_percent_24h FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY change_percent_24h ASC LIMIT 5"
    }
   ]
  },
  {
   "title": "Market Overview (Top 100)",
   "type": "table",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 16 },
   "targets": [
    {
     "rawSql": "SELECT rank, name, symbol, price_usd, high_24h, low_24h, ath, ath_change_percentage, market_cap_usd, volume_24h_usd, change_percent_24h FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY rank ASC"
    }
   ]
  }
 ]
}