{
 "title": "Crypto BIG DATA Dashboard",
 "tags": [
  "airflow",
  "crypto",
  "bigdata"
 ],
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "symbol",
    "query": "SELECT DISTINCT symbol FROM crypto_prices ORDER BY symbol"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Price: $symbol",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT price_usd, symbol FROM crypto_prices WHERE symbol IN ($symbol) AND ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY symbol ASC"
    }
   ]
  },
  {
   "title": "Price History: $symbol",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT ingestion_timestamp AS time, price_usd AS value, symbol as metric FROM crypto_prices WHERE symbol IN ($symbol) AND $__timeFilter(ingestion_timestamp) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Market Dominance (Top 5)",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 10, "w": 8, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT name, market_cap_usd FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY market_cap_usd DESC LIMIT 5"
    }
   ]
  },
  {
   "title": "Top Gainers (24h)",
   "type": "bargauge",
   "gridPos": { "x": 8, "y": 10, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT name, change_percent_24h FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY change_percent_24h DESC LIMIT 5"
    }
   ]
  },
  {
   "title": "Top Losers (24h)",
   "type": "bargauge",
   "gridPos": { "x": 16, "y": 10, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT name, change_percent_24h FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY change_percent_24h ASC LIMIT 5"
    }
   ]
  },
  {
   "title": "Market Overview (Top 100)",
   "type": "table",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 16 },
   "targets": [
    {
     "rawSql": "SELECT rank, name, symbol, price_usd, high_24h, low_24h, ath, ath_change_percentage, market_cap_usd, volume_24h_usd, change_percent_24h FROM crypto_prices WHERE ingestion_timestamp = (SELECT MAX(ingestion_timestamp) FROM crypto_prices) ORDER BY rank ASC"
    }
   ]
  }
 ]
}